DATASET_DIR = '/root/src/backend/datasets'

import numpy as np

SUPPORT_ROBOTS = [
    {
        'name': 'test_arm',
        'role': 'single_arm',
        'company': 'Test',
        'joint_dim': 7,
        'joint_names': ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "gripper"],
        'joint_lower_bounds': [-2.618, 0, -2.618, -1.745, -1.22, -2.094, 0],
        'joint_upper_bounds': [2.618, 2.618, 0, 1.745, 1.22, 2.094, 0.087],
        'read_topic': '/joint_states_single',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/joint_states',
        'write_topic_msg': 'sensor_msgs/JointState',
        'tool_inner': True,
        'tool_index': [6],
        'custom_fields': [],
        'urdf_path': '/root/ros2_ws/src/piper_ros/src/piper_description/urdf/piper_description.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/piper_ros/src/piper_description/',
        'ik_setting': {
            'joints_to_lock': [
                'joint6_to_gripper_base', 'joint7', 'joint8'
            ],
            'ee_definitions': [('ee', 'joint7', None)],
        },
    },
    {
        'name': 'piper',
        'role': 'single_arm',
        'company': 'Piper',
        'joint_dim': 7,
        'joint_names': ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6", "gripper"],
        'joint_lower_bounds': [-2.618, 0, -2.618, -1.745, -1.22, -2.094, 0],
        'joint_upper_bounds': [2.618, 2.618, 0, 1.745, 1.22, 2.094, 0.087],
        'read_topic': '/joint_states_single',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/joint_states',
        'write_topic_msg': 'sensor_msgs/JointState',
        'tool_inner': True,
        'tool_index': [6],
        'custom_fields': ['can_port'],
        'urdf_path': '/root/ros2_ws/src/piper_ros/src/piper_description/urdf/piper_description.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/piper_ros/src/piper_description/',
        'ik_setting': {
            'joints_to_lock': [
                'joint6_to_gripper_base', 'joint7', 'joint8'
            ],
            'ee_definitions': [('ee', 'joint7', None)],
        },
    },
    {
        'name': 'piper(no gripper)',
        'role': 'single_arm',
        'company': 'Piper',
        'joint_dim': 6,
        'joint_names': ["joint1", "joint2", "joint3", "joint4", "joint5", "joint6"],
        'joint_lower_bounds': [-2.618, 0, -2.618, -1.745, -1.22, -2.094],
        'joint_upper_bounds': [2.618, 2.618, 0, 1.745, 1.22, 2.094],
        'read_topic': '/joint_states_single',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/joint_states',
        'write_topic_msg': 'sensor_msgs/JointState',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['can_port'],
        'urdf_path': '/root/ros2_ws/src/piper_ros/src/piper_description/urdf/piper_no_gripper_description.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/piper_ros/src/piper_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'joint6', np.array([0.20, 0, 0]).T)],
        },
    },
    {
        'name': 'tm_12',
        'role': 'single_arm',
        'company': 'OMRON',
        'joint_dim': 6,
        'joint_names': ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"],
        'joint_lower_bounds': [-6.283, -6.283, -2.827, -6.283, -6.283, -6.283],
        'joint_upper_bounds': [6.283, 6.283, 2.827, 6.283, 6.283, 6.283],
        'read_topic': '/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'service',
        'write_topic': '/send_script',
        'write_topic_msg': 'tm_msgs/srv/SendScript',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/tm2_ros2/tm_description/urdf/tm12s.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/tm2_ros2/tm_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'joint_6', np.array([0, 0, 0.15]).T)],
        },
    },
    {
        'name': 'tm_12s',
        'role': 'single_arm',
        'company': 'OMRON',
        'joint_dim': 6,
        'joint_names': ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"],
        'joint_lower_bounds': [-6.283, -6.283, -2.827, -6.283, -6.283, -6.283],
        'joint_upper_bounds': [6.283, 6.283, 2.827, 6.283, 6.283, 6.283],
        'read_topic': '/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'service',
        'write_topic': '/send_script',
        'write_topic_msg': 'tm_msgs/srv/SendScript',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/tm2_ros2/tm_description/urdf/tm12s.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/tm2_ros2/tm_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'joint_6', np.array([0, 0, 0.15]).T)],
        },
    },
    {
        'name': 'tm_12_robotiq',
        'role': 'single_arm',
        'company': 'OMRON',
        'joint_dim': 7,
        'joint_names': ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6", "gripper"],
        'joint_lower_bounds': [-6.283, -6.283, -2.827, -6.283, -6.283, -6.283, 0.0],
        'joint_upper_bounds': [6.283, 6.283, 2.827, 6.283, 6.283, 6.283, 0.85],
        'read_topic': '/feedback_states',
        'read_topic_msg': 'tm_msgs/msg/FeedbackState',
        'write_type': 'service',
        'write_topic': '/send_script',
        'write_topic_msg': 'tm_msgs/srv/SendScript',
        'tool_inner': True,
        'tool_index': [6],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/tm2_ros2/tm_description/urdf/tm12s.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/tm2_ros2/tm_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'joint_6', np.array([0, 0, 0.15]).T)],
        },
    },
    {
        'name': 'rb3_730es_u',
        'role': 'single_arm',
        'company': 'Rainbow Robotics',
        'joint_dim': 6,
        'joint_names': ["base", "shoulder", "elbow", "wrist1", "wrist2", "wrist3"],
        'joint_lower_bounds': [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14],
        'joint_upper_bounds': [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
        'read_topic': '/rbpodo/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/position_controllers/commands',
        'write_topic_msg': 'std_msgs/Float64MultiArray',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/rbpodo_ros2/rbpodo_description/robots/rb3_730es_u.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/rbpodo_ros2/rbpodo_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'tcp_joint', None)],
        },
    },
    {
        'name': 'rb5_850e',
        'role': 'single_arm',
        'company': 'Rainbow Robotics',
        'joint_dim': 6,
        'joint_names': ["base", "shoulder", "elbow", "wrist1", "wrist2", "wrist3"],
        'joint_lower_bounds': [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14],
        'joint_upper_bounds': [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
        'read_topic': '/rbpodo/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/position_controllers/commands',
        'write_topic_msg': 'std_msgs/Float64MultiArray',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        # 'urdf_path': '/ros2_ws/src/rbpodo_ros2/rbpodo_description/robots/rb5_850e.urdf',
        # 'urdf_package_dir': '/ros2_ws/src/rbpodo_ros2/rbpodo_description/',
        # 'ik_setting': {
        #     'joints_to_lock': [],
        #     'ee_definitions': [('ee', 'tcp_joint', None)],
        # },
    },
    {
        'name': 'kinova_gen3_7dof_robotiq_2f_85',
        'role': 'single_arm',
        'company': 'Kinova',
        'joint_dim': 7,
        'joint_names': ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6", "joint_7"],
        'joint_lower_bounds': [-3.14, -3.14, -3.14, -3.14, -3.14, -3.14, -3.14],
        'joint_upper_bounds': [3.14, 3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
        'read_topic': '/joint_trajectory_controller/controller_state',
        'read_topic_msg': 'control_msgs/JointTrajectoryControllerState',
        'write_topic': '/joint_trajectory_controller/joint_trajectory',
        'write_topic_msg': 'trajectory_msgs/JointTrajectory',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/ros2_kortex/kortex_description/robots/gen3_7dof.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/ros2_kortex/kortex_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [
                # ('ee', 'joint_7', np.array([0, 0, -0.2]).T)
                ('ee', 'joint_7', np.array([0, 0, 0]).T)
            ],
            'gravity_compensate': 0.00003,  # z축 gravity 보상값 (m). 로봇이 아래로 처질 때 양수로 설정
        },
    },
    # {
    #     'name': 'ur3',
    #     'role': 'single_arm',
    #     'company': 'Universal Robots',
    # },
    # {
    #     'name': 'ur5',
    #     'role': 'single_arm',
    #     'company': 'Universal Robots',
    # },
    # {
    #     'name': 'ur10',
    #     'role': 'single_arm',
    #     'company': 'Universal Robots',
    # },
    # {
    #     'name': 'ur5e',
    #     'role': 'single_arm',
    #     'company': 'Universal Robots',
    # },
    # {
    #     'name': 'h1',
    #     'role': 'dual_arm',
    #     'company': 'Unitree',
    # },
    {
        'name': 'fairino_fr5',
        'role': 'single_arm',
        'company': 'Fairino',
        'joint_dim': 6,
        'joint_names': ["j1", "j2", "j3", "j4", "j5", "j6"],
        'joint_lower_bounds': [-3.0543, -4.6251, -2.8274, -4.6251, -3.0543, -3.0543],
        'joint_upper_bounds': [3.0543, 1.4835, 2.8274, 1.4835, 3.0543, 3.0543],
        'read_topic': '/nonrt_state_data',
        'read_topic_msg': 'fairino_msgs/msg/RobotNonrtState',
        'write_type': 'service',
        'write_topic': '/fairino_remote_command_service',
        'write_topic_msg': 'fairino_msgs/srv/RemoteCmdInterface',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/frcobot_ros2/fairino_description/urdf/fairino5_v6.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/frcobot_ros2/fairino_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'j6', np.array([0, 0, 0.1]).T)],
        },
    },
    {
        'name': 'jaka_zu12',
        'role': 'single_arm',
        'company': 'JAKA',
        'joint_dim': 6,
        'joint_names': ["joint_1", "joint_2", "joint_3", "joint_4", "joint_5", "joint_6"],
        'joint_lower_bounds': [-6.28, -1.48, -3.05, -1.48, -6.28, -6.28],
        'joint_upper_bounds': [6.28, 4.62, 3.05, 4.62, 6.28, 6.28],
        'read_topic': '/jaka_driver/joint_position',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'service',
        'write_topic': '/jaka_driver/servo_j',
        'write_topic_msg': 'jaka_msgs/srv/ServoMove',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address'],
        'urdf_path': '/root/ros2_ws/src/jaka_ros2/src/jaka_description/urdf/jaka_zu12.urdf',
        'urdf_package_dir': '/root/ros2_ws/src/jaka_ros2/src/jaka_description/',
        'ik_setting': {
            'joints_to_lock': [],
            'ee_definitions': [('ee', 'joint_6', None)],
        },
    },
    {
        'name': 'robotiq_2f_85',
        'role': 'tool',
        'company': 'Robotiq',
        'joint_dim': 1,
        'joint_names': ['robotiq_85_left_knuckle_joint'],
        'joint_lower_bounds': [0.0],
        'joint_upper_bounds': [0.85],
        'read_topic': '/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'action',
        'write_topic': '/robotiq_gripper_controller/gripper_cmd',
        'write_topic_msg': 'control_msgs/action/GripperCommand',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['serial_port'],
    },
    {
        'name': '2FG7',
        'role': 'tool',
        'company': 'OnRobot',
        'joint_dim': 1,
        'joint_names': ['gripper_pos'],
        'joint_lower_bounds': [0.1],
        'joint_upper_bounds': [0.48],
        'read_topic': '/joint_states',
        'read_topic_msg': 'sensor_msgs/JointState',
        'write_type': 'topic',
        'write_topic': '/command',
        'write_topic_msg': 'sensor_msgs/JointState',
        'tool_inner': False,
        'tool_index': [],
        'custom_fields': ['ip_address', 'port'],
    }
]

SUPPORT_SENSORS = [
    {
        'name': 'realsense_d435_color',
        'company': 'Intel',
        'role': 'rgb_camera',
        'topic_type': 'color',
        'read_topic': '/camera/color/image_raw/compressed',
        'read_topic_msg': 'sensor_msgs/CompressedImage',
        'custom_fields': ['serial_no'],
        'resolution': [1280, 720]
    },
    {
        'name': 'realsense_d405_color',
        'company': 'Intel',
        'role': 'rgb_camera',
        'topic_type': 'color',
        'read_topic': '/camera/color/image_rect_raw/compressed',
        'read_topic_msg': 'sensor_msgs/CompressedImage',
        'custom_fields': ['serial_no'],
        'resolution': [848, 480]
    },
    {
        'name': 'webcam_color',
        'company': 'Logitec',
        'role': 'rgb_camera',
        'topic_type': 'color',
        'read_topic': '/image_raw/compressed',
        'read_topic_msg': 'sensor_msgs/CompressedImage',
        'custom_fields': ['device_index'],
        'resolution': [600, 480]
    },
    {
        'name': 'kinova_vision_color',
        'company': 'Kinova',
        'role': 'rgb_camera',
        'topic_type': 'color',
        'read_topic': '/color/image_raw/compressed',
        'read_topic_msg': 'sensor_msgs/CompressedImage',
        'custom_fields': ['ip_address'],
        'resolution': [1980, 1080]
    }
]

def get_robot_by_name(name):
    return next((robot for robot in SUPPORT_ROBOTS if robot.get('name') == name), None)

def get_sensor_by_name(name):
    return next((sensor for sensor in SUPPORT_SENSORS if sensor.get('name') == name), None)